workflows:
  ios-workflow:
    name: iOS Workflow
    integrations:
      app_store_connect: aplikacija
    publishing:
      app_store_connect:
        auth: integration
        # api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        # key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        # issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        beta_groups:
          - Testers
    environment:
      ios_signing:
        distribution_type: app_store # or: ad_hoc | development | enterprise
        bundle_identifier: lt.pro3D.kosmosas
      vars:
        APP_ID: 6448805235
      flutter: stable
      groups:
        - ios_credentials
      vars:
        BUNDLE_ID: 'lt.pro3D.kosmosas'
    scripts:
      - name: Set up code signing settings on Xcode project
        script: | 
          xcode-project use-profiles
      - name: Get Flutter packages
        script: | 
          flutter packages pub get --verbose
      - name: Install pods
        script: | 
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa
        script: | 
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist \
            --build-name=1.0.10 \
            --build-number=10
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
